name: fend cd

on:
  push:
    branches:
      - main
    paths:
      - 'fend/**'
      - '.github/workflows/bend-ci.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to SSH
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.DNS_NAME }}
          USER_NAME: ${{ secrets.USERNAME_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key &&
          chmod 600 private_key &&
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} &&
          docker stop $(docker ps -q) &&
          docker rm $(docker ps -aq) &&
          docker pull ghcr.io/test-organization-package/fend:latest &&
          docker run --name "first-deploy" -p 80:3000 ghcr.io/test-organization-package/fend:latest
