name: fend ci

on:
  push

jobs:
  build-image:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build image
        run: |
          echo "${{ secrets.PACKAGE_TOKEN }}" | docker login ghcr.io --username "${{ vars.USERNAME }}" --password-stdin &&
          docker build . --file fend/Dockerfile --tag ghcr.io/test-organization-package/fend:latest &&
          docker push ghcr.io/test-organization-package/fend:latest
  run-testcases:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
